title: Cheng Lu’s Homepage
logo: profile.jpg
description: I am now working as a research associate in Center for Computational Imaging & Personalized Diagnostics, Case Western Reserve University, US. My research interest includes biomedical image analysis, computer vision and pattern recognition. My current project is on the digital histological image analysis.
theme: jekyll-theme-minimal
