title: Cheng Lu’s Homepage
logo: assets/img/logo.png
email: cxl884@case.edu
research_gate: https://www.researchgate.net/profile/Cheng_Lu5?ev=hdr_xprf
address: Department of Biomedical Engineering, Case Western Reserve University, 2071 Martin Luther King Drive, OH, 44106-7207, Wickenden 525 
profile: I am now working as a research associate in Center for Computational Imaging & Personalized Diagnostics, Case Western Reserve University, US. My research interest includes biomedical image analysis, computer vision and pattern recognition. My current project is on the digital histological image analysis.
theme: jekyll-theme-minimal
